export const CATEGORIES = {
  math: {
    label: 'Math',
    icon: '∑',
    color: 'amber',
    bg: 'bg-amber-50 dark:bg-amber-950/20',
    iconBg: 'bg-amber-100 dark:bg-amber-900/30',
    text: 'text-amber-700 dark:text-amber-400',
    border: 'border-amber-200 dark:border-amber-800/60',
    path: '/math',
    description: 'Arithmetic, algebra, statistics & more',
  },
  financial: {
    label: 'Financial',
    icon: '$',
    color: 'orange',
    bg: 'bg-orange-50 dark:bg-orange-950/20',
    iconBg: 'bg-orange-100 dark:bg-orange-900/30',
    text: 'text-orange-700 dark:text-orange-400',
    border: 'border-orange-200 dark:border-orange-800/60',
    path: '/financial',
    description: 'Mortgage, loans, investments & savings',
  },
  health: {
    label: 'Health',
    icon: '♥',
    color: 'red',
    bg: 'bg-red-50 dark:bg-red-950/20',
    iconBg: 'bg-red-100 dark:bg-red-900/30',
    text: 'text-red-700 dark:text-red-400',
    border: 'border-red-200 dark:border-red-800/60',
    path: '/health',
    description: 'BMI, calories, body fat & fitness',
  },
  datetime: {
    label: 'Date & Time',
    icon: '📅',
    color: 'yellow',
    bg: 'bg-yellow-50 dark:bg-yellow-950/20',
    iconBg: 'bg-yellow-100 dark:bg-yellow-900/30',
    text: 'text-yellow-700 dark:text-yellow-400',
    border: 'border-yellow-200 dark:border-yellow-800/60',
    path: '/datetime',
    description: 'Age, date difference, countdowns',
  },
  converters: {
    label: 'Converters',
    icon: '⇄',
    color: 'stone',
    bg: 'bg-stone-50 dark:bg-stone-950/20',
    iconBg: 'bg-stone-100 dark:bg-stone-900/30',
    text: 'text-stone-700 dark:text-stone-400',
    border: 'border-stone-200 dark:border-stone-800/60',
    path: '/converters',
    description: 'Length, weight, temperature & more',
  },
  other: {
    label: 'Other',
    icon: '⚙',
    color: 'zinc',
    bg: 'bg-zinc-50 dark:bg-zinc-950/20',
    iconBg: 'bg-zinc-100 dark:bg-zinc-900/30',
    text: 'text-zinc-700 dark:text-zinc-400',
    border: 'border-zinc-200 dark:border-zinc-800/60',
    path: '/other',
    description: 'GPA, grades, fuel economy & passwords',
  },
};

export const ROUTES = [
  // Math
  { path: '/math/basic', component: 'BasicCalculator', category: 'math', title: 'Basic Calculator', description: 'Add, subtract, multiply and divide', keywords: ['add', 'subtract', 'multiply', 'divide', 'arithmetic', 'plus', 'minus'] },
  { path: '/math/scientific', component: 'ScientificCalculator', category: 'math', title: 'Scientific Calculator', description: 'Advanced functions: sin, cos, log, powers', keywords: ['scientific', 'sin', 'cos', 'tan', 'log', 'square root', 'trigonometry'] },
  { path: '/math/percentage', component: 'PercentageCalculator', category: 'math', title: 'Percentage Calculator', description: 'What is X% of Y? X is what % of Y?', keywords: ['percent', 'percentage', 'ratio', 'proportion'] },
  { path: '/math/fraction', component: 'FractionCalculator', category: 'math', title: 'Fraction Calculator', description: 'Add, subtract, multiply and divide fractions', keywords: ['fraction', 'numerator', 'denominator', 'simplify', 'mixed number'] },
  { path: '/math/triangle', component: 'TriangleCalculator', category: 'math', title: 'Triangle Calculator', description: 'Area, perimeter, angles and sides', keywords: ['triangle', 'area', 'perimeter', 'hypotenuse', 'pythagorean', 'angle'] },
  { path: '/math/square-root', component: 'SquareRootCalculator', category: 'math', title: 'Square Root Calculator', description: 'Calculate square roots and nth roots', keywords: ['square root', 'sqrt', 'radical', 'root'] },
  { path: '/math/exponent', component: 'ExponentCalculator', category: 'math', title: 'Exponent Calculator', description: 'Calculate powers and exponents', keywords: ['exponent', 'power', 'base', 'squared', 'cubed'] },
  { path: '/math/logarithm', component: 'LogarithmCalculator', category: 'math', title: 'Logarithm Calculator', description: 'Natural log, log base 10, any base', keywords: ['log', 'logarithm', 'natural log', 'ln', 'log10'] },
  { path: '/math/standard-deviation', component: 'StandardDeviationCalculator', category: 'math', title: 'Standard Deviation', description: 'Mean, variance and standard deviation', keywords: ['standard deviation', 'mean', 'variance', 'statistics', 'average'] },
  { path: '/math/random-number', component: 'RandomNumberGenerator', category: 'math', title: 'Random Number Generator', description: 'Generate random numbers in a range', keywords: ['random', 'random number', 'dice', 'generate'] },

  // Financial
  { path: '/financial/mortgage', component: 'MortgageCalculator', category: 'financial', title: 'Mortgage Calculator', description: 'Monthly payments and amortization schedule', keywords: ['mortgage', 'home loan', 'monthly payment', 'house', 'amortization', 'real estate'] },
  { path: '/financial/loan', component: 'LoanCalculator', category: 'financial', title: 'Loan Calculator', description: 'Personal loan monthly payments and totals', keywords: ['loan', 'personal loan', 'monthly payment', 'interest rate', 'term'] },
  { path: '/financial/auto-loan', component: 'AutoLoanCalculator', category: 'financial', title: 'Auto Loan Calculator', description: 'Car loan payments with trade-in & down payment', keywords: ['auto loan', 'car loan', 'vehicle', 'trade-in', 'down payment'] },
  { path: '/financial/compound-interest', component: 'CompoundInterestCalculator', category: 'financial', title: 'Compound Interest', description: 'Calculate compound interest over time', keywords: ['compound interest', 'interest', 'savings', 'growth', 'APY'] },
  { path: '/financial/simple-interest', component: 'SimpleInterestCalculator', category: 'financial', title: 'Simple Interest', description: 'Calculate simple interest and total amount', keywords: ['simple interest', 'interest', 'principal', 'rate'] },
  { path: '/financial/investment', component: 'InvestmentCalculator', category: 'financial', title: 'Investment Calculator', description: 'Future value with regular contributions', keywords: ['investment', 'future value', 'portfolio', 'returns', 'contributions'] },
  { path: '/financial/retirement', component: 'RetirementCalculator', category: 'financial', title: 'Retirement Calculator', description: 'How much you need to retire', keywords: ['retirement', '401k', 'savings', 'pension', 'nest egg'] },
  { path: '/financial/tip', component: 'TipCalculator', category: 'financial', title: 'Tip Calculator', description: 'Calculate tip and split the bill', keywords: ['tip', 'gratuity', 'bill split', 'restaurant'] },
  { path: '/financial/sales-tax', component: 'SalesTaxCalculator', category: 'financial', title: 'Sales Tax Calculator', description: 'Calculate sales tax and final price', keywords: ['sales tax', 'tax', 'VAT', 'price after tax'] },
  { path: '/financial/discount', component: 'DiscountCalculator', category: 'financial', title: 'Discount Calculator', description: 'Sale price after discount percentage', keywords: ['discount', 'sale', 'savings', 'coupon', 'markdown'] },

  // Health
  { path: '/health/bmi', component: 'BMICalculator', category: 'health', title: 'BMI Calculator', description: 'Body Mass Index with weight category', keywords: ['BMI', 'body mass index', 'weight', 'obesity', 'healthy weight'] },
  { path: '/health/calorie', component: 'CalorieCalculator', category: 'health', title: 'Calorie Calculator', description: 'Daily calorie needs (TDEE)', keywords: ['calorie', 'TDEE', 'BMR', 'metabolism', 'diet', 'weight loss'] },
  { path: '/health/body-fat', component: 'BodyFatCalculator', category: 'health', title: 'Body Fat Calculator', description: 'Body fat percentage (US Navy method)', keywords: ['body fat', 'body fat percentage', 'waist', 'neck', 'navy method'] },
  { path: '/health/pregnancy', component: 'PregnancyDueDateCalculator', category: 'health', title: 'Pregnancy Due Date', description: 'Calculate your baby due date', keywords: ['pregnancy', 'due date', 'LMP', 'baby', 'gestation'] },
  { path: '/health/ovulation', component: 'OvulationCalculator', category: 'health', title: 'Ovulation Calculator', description: 'Fertile window and ovulation date', keywords: ['ovulation', 'fertility', 'cycle', 'fertile window', 'period'] },
  { path: '/health/ideal-weight', component: 'IdealWeightCalculator', category: 'health', title: 'Ideal Weight Calculator', description: 'Ideal body weight by height and gender', keywords: ['ideal weight', 'healthy weight', 'Devine formula', 'height'] },

  // Date & Time
  { path: '/datetime/date-difference', component: 'DateDifferenceCalculator', category: 'datetime', title: 'Date Difference', description: 'Days, weeks, months between two dates', keywords: ['date difference', 'days between', 'duration', 'how many days'] },
  { path: '/datetime/age', component: 'AgeCalculator', category: 'datetime', title: 'Age Calculator', description: 'Exact age in years, months and days', keywords: ['age', 'birthday', 'birthdate', 'how old'] },
  { path: '/datetime/time', component: 'TimeCalculator', category: 'datetime', title: 'Time Calculator', description: 'Add or subtract hours, minutes, seconds', keywords: ['time', 'hours', 'minutes', 'seconds', 'add time', 'subtract time'] },
  { path: '/datetime/days-until', component: 'DaysUntilCalculator', category: 'datetime', title: 'Days Until Calculator', description: 'Countdown to any future date', keywords: ['days until', 'countdown', 'days remaining', 'future date'] },

  // Converters
  { path: '/converters/length', component: 'LengthConverter', category: 'converters', title: 'Length Converter', description: 'Meters, feet, miles, inches and more', keywords: ['length', 'meter', 'feet', 'miles', 'km', 'inch', 'convert'] },
  { path: '/converters/weight', component: 'WeightConverter', category: 'converters', title: 'Weight Converter', description: 'Kilograms, pounds, ounces and more', keywords: ['weight', 'kg', 'pounds', 'lbs', 'ounce', 'gram', 'convert'] },
  { path: '/converters/temperature', component: 'TemperatureConverter', category: 'converters', title: 'Temperature Converter', description: 'Celsius, Fahrenheit and Kelvin', keywords: ['temperature', 'celsius', 'fahrenheit', 'kelvin', 'convert'] },
  { path: '/converters/volume', component: 'VolumeConverter', category: 'converters', title: 'Volume Converter', description: 'Liters, gallons, cups and more', keywords: ['volume', 'liter', 'gallon', 'cup', 'fluid ounce', 'convert'] },
  { path: '/converters/area', component: 'AreaConverter', category: 'converters', title: 'Area Converter', description: 'Square meters, acres, hectares and more', keywords: ['area', 'square meter', 'acre', 'hectare', 'square foot', 'convert'] },
  { path: '/converters/speed', component: 'SpeedConverter', category: 'converters', title: 'Speed Converter', description: 'mph, kph, m/s, knots and more', keywords: ['speed', 'mph', 'kph', 'meters per second', 'knots', 'convert'] },

  // Other
  { path: '/other/grade', component: 'GradeCalculator', category: 'other', title: 'Grade Calculator', description: 'Weighted grades and final percentage', keywords: ['grade', 'score', 'assignment', 'weighted average', 'GPA'] },
  { path: '/other/gpa', component: 'GPACalculator', category: 'other', title: 'GPA Calculator', description: 'Calculate GPA from course grades', keywords: ['GPA', 'grade point average', 'college', 'courses', 'credits'] },
  { path: '/other/fuel-economy', component: 'FuelEconomyCalculator', category: 'other', title: 'Fuel Economy Calculator', description: 'MPG, L/100km and fuel cost', keywords: ['fuel economy', 'MPG', 'gas mileage', 'fuel cost', 'liters per 100km'] },
  { path: '/other/password', component: 'PasswordGenerator', category: 'other', title: 'Password Generator', description: 'Strong random password generator', keywords: ['password', 'random password', 'secure', 'generator', 'strong password'] },
];
